apps/posts/urls.py
from django.conf.urls import url

from .views import get_media, like_post, post_detail, posts_add, share_post

urlpatterns = [
    url(r'^add/', posts_add, name='add'),
    url(r'^(?P<post_id>[0-9a-f-]+)/like', like_post, name='like'),
    url(r'^(?P<post_id>[0-9a-f-]+)/share', share_post, name='share'),
    url(r'^api/(?P<post_id>[0-9a-f-]+)', post_detail, name='post_detail'),
    url(r'^api/media/(?P<media_id>[0-9]+)/', get_media, name='get_media'),
]

apps/user_profile/urls.py
from django.conf.urls import url

from .views import follow_user, profile_photo, user_profile

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/$', user_profile, name='user_profile'),
    url(r'^(?P<username>[\w.@+-]+)/follow$', follow_user, name='follow_user'),
    url(r'^(?P<username>[\w.@+-]+)/profile_photo$',
        profile_photo, name="profile_photo"),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.templatetags.static import static as static_tag
from django.views.generic import RedirectView
from feed.views import LandingView

urlpatterns = [
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', LandingView.as_view(), name='landing_page'),
    url(r'^settings/', include('settings.urls', namespace='settings')),
    url(r'^user/', include('user_profile.urls', namespace='user_profile')),
    url(r'^', include('search.urls', namespace='search')),
    url(r'favicon.ico/$', RedirectView.as_view(
        url=static_tag('img/favicon.png'),
        permanent=True)),
    url(r'posts/', include('posts.urls', namespace='posts')),
    url(r'home/', include('feed.urls', namespace='feeds')),
]

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.errors.views.not_found'
handler500 = 'apps.errors.views.server_error'
handler403 = 'apps.errors.views.permission_denied'
handler400 = 'apps.errors.views.bad_request'

apps/posts/models.py
import os
import random
import re
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.db.models import F, signals
from django.dispatch import receiver
from django.utils import timezone

from .model_validators import validate_file_extension_posts_media


def upload_posts_media_to(instance, filename):
    username = instance.post.user.username
    _, file_extension = os.path.splitext(filename)
    filename = str(random.getrandbits(64)) + file_extension
    return f'posts/{username}/{filename}'


class PostManager(models.Manager):
    def share(self, user, post, quote_text=None):
        shared_post_parent = None

        # set the new shared post's parent as same as original post parent
        if post.parent:
            shared_post_parent = post.parent

        # if the post that is to be shared is also shared, go for the original post
        # post -> shared_post -> shared_post__shared_post
        if post.shared_post:
            post = post.shared_post

        # check if shared_post already exists
        shared_post = self.get_queryset().filter(
            user=user, parent=shared_post_parent
        ).filter(
            created__year=timezone.now().year,
            created__month=timezone.now().month,
            created__day=timezone.now().day,
            shared_post__isnull=False,
        )
        # if post has already been shared, delete that post, i.e. toggle share
        if shared_post.exists():
            shared_post.delete()
            return None

        # save the new post
        share_post = self.model(
            parent=shared_post_parent,
            user=user,
            text=quote_text,
            shared_post=post,
        )
        share_post.save()

        return share_post

    def like(self, user, post):
        if user in post.likes.all():
            is_liked = False
            post.likes.remove(user)
        else:
            is_liked = True
            post.likes.add(user)
        return is_liked


class PostMedia(models.Model):
    media = models.ImageField(upload_to=upload_posts_media_to)
    media_type = models.CharField(default='image', max_length=6)
    post = models.ForeignKey('Post', related_name='posts_media')
    uploaded = models.DateTimeField(auto_now_add=True)


class PostsMetadata(models.Model):
    views = models.IntegerField(default=0)
    impressions = models.IntegerField(default=0)
    post = models.OneToOneField('Post', blank=True)


class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    parent = models.ForeignKey(
        'self', blank=True, null=True, related_name='post_childs')
    user = models.ForeignKey(User)
    text = models.CharField(max_length=500, null=True)
    likes = models.ManyToManyField(User, blank=True, related_name='liked')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    shared_post = models.ForeignKey('self', blank=True, null=True,
                                    verbose_name='If shared only',
                                    related_name='post_shared')

    objects = PostManager()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f'{self.id} : {self.user}'

    def create_post(self, user, text):
        self._create(user=user, text=text)

    def create_reply(self, user, text, parent):
        self._create(user=user, text=text, parent=parent)

    def _create(self, user, text, parent=None):
        self.objects.create(user=user, text=text, parent=parent)

    def get_parent(self):
        x = self.parent if self.parent else None
        return x

    def like(self, user):
        return self.objects.like(user=user, post=self)

    def get_childs(self):
        childs = Post.objects.filter(parent=self)
        return childs if childs.exists() else None

    def get_medias(self):
        return self.posts_media.all() if self.posts_media.exists() else None

    def fullName(self):
        # Any expensive calculation on instance data
        # This returning value is cached and not calculated again
        return self.user.first_name + " " + self.user.last_name


class Tag(models.Model):
    tag = models.CharField(max_length=140)
    created = models.DateTimeField(auto_now_add=True)
    count = models.IntegerField(default=0)

    def __str__(self):
        return f'#{self.tag}'


@receiver(signals.post_save, sender=Post)
def create_tags(sender, instance, created, *args, **kwargs):
    if created:
        tag_regex = r'#(?P<tag>[\w\d-]+)'
        if instance.text:
            tags = re.findall(tag_regex, instance.text)
            for tag in tags:
                _tag = Tag.objects.filter(tag__iexact=tag)
                if _tag.exists():
                    _tag.update(count=F('count') + 1)
                else:
                    Tag.objects.create(tag=tag)


@receiver(signals.post_save, sender=Post)
def create_metadata_for_post(sender, instance, created, **kwargs):
    if created:
        PostsMetadata.objects.create(post=instance)

apps/posts/forms.py
from django import forms
from django.forms import (BaseModelFormSet, ValidationError,
                          modelformset_factory)

from .models import Post, PostMedia


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'shared_post']

    def save(self, user, shared_post_id=None, parent_id=None, commit=True, *args, **kwargs):
        instance = super().save(commit=False, )
        instance.user = user
        if shared_post_id:
            post = Post.objects.get(pk=shared_post_id)
            if post.shared_post:
                instance.shared_post = post.shared_post
                instance.parent = post.shared_post.parent
            else:
                instance.shared_post = post
                instance.parent = post.parent
        if parent_id:
            post = Post.objects.get(pk=parent_id)
            if post:
                instance.parent = post
        if commit:
            instance.save()
        return instance

    def clean(self, *args, **kwargs):
        super().clean(*args, **kwargs)
        if len(self.cleaned_data.get('text')) > 140:
            raise ValidationError(
                "Character limit exceeded. Posts should be less than 140 characters.")


class BasePostMediaFormSet(BaseModelFormSet):
    def save(self, post, commit=True):
        instances = super().save(commit=False)
        for instance in instances:
            instance.post = post
            if commit:
                instance.save()
        return instances


PostMediaFormSet = modelformset_factory(
    PostMedia,
    fields=('media',),
    extra=0,
    formset=BasePostMediaFormSet
)

apps/posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import redirect, render, reverse

from feed.templatetags import post_include

from .forms import PostForm, PostMediaFormSet
from .models import Post, PostMedia
from .serializers import PostSerializer


@login_required
def posts_add(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST)
        media_form_set = PostMediaFormSet(request.POST, request.FILES)
        if post_form.is_valid() and media_form_set.is_valid():
            shared_post_id = request.POST.get('shared_post')
            parent_id = request.POST.get('parent')
            if not shared_post_id:
                shared_post_id = None
            if not parent_id:
                parent_id = None
            post = post_form.save(request.user, shared_post_id, parent_id)
            media_form_set.save(post)

            next_url = request.GET.get('next')
            if next_url:
                return redirect(next_url)
            else:
                return redirect(reverse('feeds:home'))
        return render(request, 'posts/post_add.html', {
            'mediaformset': media_form_set,
            'post_form': post_form,
        })
    else:
        return redirect(reverse('feeds:home'))

@login_required
def like_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    is_liked = Post.objects.like(request.user, post)
    likes_count = post.likes.count()
    return JsonResponse({"done": is_liked, 'likes_count': likes_count})


@login_required
def share_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    shared_post = Post.objects.share(user=request.user, post=post)
    is_shared = False
    if shared_post:
        is_shared = True
    shares_count = post.post_shared.count()
    return JsonResponse({'done': is_shared, 'shares_count': shares_count})


@login_required
def post_detail(request, post_id):
    post = post_include.get_all_posts().get(pk=post_id)
    print(PostSerializer())
    serialized_data = PostSerializer(post, context={'request': request}).data
    return JsonResponse(serialized_data, safe=False)


@login_required
def get_media(request, media_id):
    media = PostMedia.objects.get(pk=media_id)
    return redirect(media.media.url)

apps/posts/templates/posts/post.html
{% load static %}
{% load humanize %}
{% load post_include %}
<div class="media" postId="{{post.id}}">
        <div class="pull-left" href="{% url 'user_profile:user_profile' post.user %}">
         <div class="avatar">
            <a href="{% url 'user_profile:user_profile' username=post.user.username %}">
              <img class="media-object" src="{% if post.user.user_details.profile_photo %}{{ post.user.user_details.profile_photo.url }}{%else%}{% static 'img/default_profile.jpg' %}{% endif %}" alt="..." />
            </a>
            </div>
        </div>
        <div class="media-body">
          <a href="{% url 'user_profile:user_profile' username=post.user.username %}"><strong>{{post.fullName}}</strong>
          <h5 class="media-heading date_created_value" value="{{post.created|date:'c'}}"><small>@{{post.user.username}} &middot; 
           <i class="status"> {% if post.shared_post %}shared <a href="{% url 'user_profile:user_profile' username=post.shared_post.user.username %}">@{{post.parent.user.username}}</a>'s post {%elif post.parent %}replied to <a href="{% url 'user_profile:user_profile' username=post.parent.user.username %}">@{{post.parent.user.username}}</a>{% else%}posted{% endif%}</i>
            <i class="natural-date">{{post.created|naturaltime}}</i></small></h5>
          </a>
          {% if post.text %}
          <p>{{post.text}}</p>
          {% endif %}
         
        
          {% if post.shared_post %}
          <div class="tweet-link">
            <div class="row">
              <div class="avatar">
                <img src="{% if post.shared_post.user.user_details.profile_photo %}{{ post.shared_post.user.user_details.profile_photo.url }}{%else%}{% static 'img/default_profile.jpg' %}{% endif %}" alt="Rounded Image" class="img-rounded img-tweet-link img-responsive">
                </div>
                <div class="col-md-8">
                    <a href="{% url 'user_profile:user_profile' username=post.shared_post.user.username %}"><strong>{{post.shared_post.fullName}}</strong>
                      <h5 class="media-heading date_created_value" value="{{post.shared_post.created|date:'c'}}"><small>@{{post.shared_post.user.username}} &middot; <i class="natural-date">{{post.shared_post.created|naturaltime}}</i></small></h5>
                      </a>
                      <a href="">
                          {% if post.shared_post.text %}
                        <p>{{post.shared_post.text}}</p>
                      {% endif %}</a>
                      <div class="my-gallery" itemscope itemtype="http://schema.org/ImageGallery">
                       {% for media in post.shared_post.posts_media.all %}
                       {% if media.media %}

                        <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
                          <a href="{{media.media.url}}" itemprop="contentUrl" data-size="{{media.media.width}}x{{media.media.height}}">
                              <img src="{{media.media.url}}" itemprop="thumbnail" alt="Image description" />
                          </a>
                          <figcaption itemprop="caption description">
                            {{post.text}}</figcaption>
                        </figure>
                        {% endif %}
                        {% endfor %}
                      </div>
                      
                </div>
              </div>
            </div>

        {% endif  %}
  <div class="my-gallery" itemscope itemtype="http://schema.org/ImageGallery">
    {% for media_post in post.posts_media.all %}
    {% if media_post.media %}

    <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
      <a href="{{media_post.media.url}}" itemprop="contentUrl" data-size="{{media_post.media.width}}x{{media_post.media.height}}">
          <img src="{{media_post.media.url}}" itemprop="thumbnail" alt="Image description" />
      </a>
      <figcaption itemprop="caption description">
        {{post.text}}</figcaption>
    </figure>

    {% endif %}
    {% endfor %}
  </div>


  <div class="media-footer">
      <a href="{% url 'posts:add'%}" class="btn btn-link reply-click">
           <i class="fa fa-comment"></i>
      </a>
      <span class="dropdown">
         <a href="" class="btn {%if post.shared %}btn-danger {% endif %} btn-link share-count" data-toggle="dropdown">
            <i class="fa fa-share-alt"></i> <i class="like-count">{{post.shared_count}}</i>
       </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton" class="">
              <a class="dropdown-item btn {%if post.shared %}btn-danger {% endif %} btn-link normal-share-click" href="{% url 'posts:share' post.id %}">Share post</a>
              <a class="dropdown-item btn {%if post.shared %}btn-danger {% endif %} btn-link share-click" href="{% url 'posts:share' post.id %}">Share with quote</a>
          </ul>
        </span>
      <a href="{% url 'posts:like' post.id %}" class="btn {%if post.post_liked %}btn-danger{% endif %} btn-link black like-click">
           <i class="fa fa-heart"></i> <i class="like-count">{{ post.likes.count }}</i>
      </a>
     
      {% comment %} <a href="{% url 'user_profile:follow_user' username=post.user.username %}">
        <i class="fa fa-user-plus">
        </i>
      </a> {% endcomment %}

  </div>
  {% for child_post in post.post_childs.all %}
  <div class="tweet-link">
      <div class="row">
        <div class="avatar">
          <img src="{% if child_post.user.user_details.profile_photo %}{{ child_post.user.user_details.profile_photo.url }}{%else%}{% static 'img/default_profile.jpg' %}{% endif %}" alt="Rounded Image" class="img-rounded img-tweet-link img-responsive">
          </div>
          <div class="col-md-8">
              <a href="{% url 'user_profile:user_profile' username=child_post.user.username %}"><strong>{{child_post.fullName}}</strong>
                <h5 class="media-heading date_created_value" value="{{child_post.created|date:'c'}}"><small>@{{child_post.user.username}} &middot; <i class="natural-date">{{child_post.created|naturaltime}}</i></small></h5>
                </a>
                <a href="">
                    {% if child_post.text %}
                  <p>{{child_post.text}}</p>
                {% endif %}</a>
                <div class="my-gallery" itemscope itemtype="http://schema.org/ImageGallery">
                 {% for media in child_post.posts_media.all %}
                 {% if media.media %}

                  <figure itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
                    <a href="{{media.media.url}}" itemprop="contentUrl" data-size="{{media.media.width}}x{{media.media.height}}">
                        <img src="{{media.media.url}}" itemprop="thumbnail" alt="Image description" />
                    </a>
                    <figcaption itemprop="caption description">
                      {{post.text}}</figcaption>
                  </figure>
                  {% endif %}
                  {% endfor %}
                </div>
                
          </div>
        </div>
      </div>

  {% endfor  %}
        </div>
</div>

apps/posts/templates/posts/post_add.html
{% load static %}



<!-- Button trigger modal -->
<button type="button" id="postAddButton" class="btn btn-floating btn-outline-default btn-primary btn-round" data-toggle="modal">
    <i class="fa fa-pencil-square-o"></i>Add Post</button>
<!-- Modal -->

<style type="text/css">
    .image-preview {
      width: 400px;
      height: 400px;
      position: relative;
      overflow: hidden;
      background-color: #ffffff;
      color: #ecf0f1;
    }
    .image-preview input {
      line-height: 200px;
      font-size: 200px;
      position: absolute;
      opacity: 0;
      z-index: 10;
    }
    .image-preview label {
        position: absolute;
        z-index: 5;
        opacity: 0.8;
        cursor: pointer;
        background-color: #bdc3c7;
        width: 200px;
        height: 50px;
        font-size: 20px;
        line-height: 50px;
        text-transform: uppercase;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        margin: auto;
        text-align: center;
    }
    textarea {
        resize: none;
    }
    .modal-body {
        max-height: calc(100vh - 300px);
        overflow-y: auto;
    }
    </style>
    
<div class="modal fade" id="postAddModal" tabindex="-1" role="dialog" data-backdrop="false" aria-labelledby="postAddModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center" id="postaddtitleheader">
                    <i class="fa fa-pencil-square-o"></i>
                    Add Post
                </h5>
                <i>[[remainingChars]]</i>
                <button type="button" class="close" id="close-post-btn" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{% url 'posts:add'%}?next={{request.path}}" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" value="" name="parent" id="reply-post-input-id">

                <div class="reply-form">
                    </div>

                <div class="modal-body">
                    {% if post_form.errors %}
                        <div class="form-control-feedback text-danger">
                            <i class="fa fa-exclamation-circle"></i>
                            {{ post_form.non_field_errors.as_text }}
                        </div>
                    {% endif %}
                    <textarea class="form-control" id="id_text" name="text" maxlength="140" type="text" placeholder="Status" cols="33" rows="5" required v-model="post_text">[[post_text]]</textarea>
                    {{ post_form.text.errors }}
                    <div class="share-form">
                                            </div>

                    <input type="hidden" value="" name="shared_post" id="share-post-input-id">
                    <div class="media-forms">
                        {{mediaformset.management_form}}
                        <div style="display:none;" id="form_template">
                            <div id='image-preview-__prefix__' class="image-preview">
                                {{ mediaformset.empty_form.as_p }}
                            </div>
                        </div><!-- stores empty form for javascript -->
                        <div id="forms">
                            <!-- here the generated forms go -->
                        </div>
                    </div>
                    <!-- Here add media button goes-->
                    <button type="button" class="btn btn-info btn-round" id="addmedia">
                        <i class="fa fa-image"></i>
                        Add Media
                    </button>
                    
                    <input type="submit" id="postformsubmit" hidden>
                    <input value="0" id="justfornum" hidden>
                </div>
            </form>
            <div class="modal-footer">
                <div class="left-side">
                    <button type="button" id="close-post-btn" class="btn btn-default btn-link" data-dismiss="modal">
                        Cancel
                    </button>
                </div>

                <div class="divider"></div>
                <div class="right-side">
                    <button type="button" class="btn btn-danger btn-link" onclick="$('#postformsubmit').click();">
                        Post
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    var app1 = new Vue({
        el: '#postAddModal',
        delimiters: ['[[', ']]'],
        data: {
            post_text: '',
        },
        computed: {
            remainingChars: function(){
                var length = 140 - this.post_text.length;
                return length;
            }
        }
    })
</script>