apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from .views import activate as activate_view
from .views import UserLoginView, logout_view, signup

app_name = 'accounts'
urlpatterns = [
    url(r'signup/$', signup, name='signup'),
    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate_view, name='activate'),

    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt',
            success_url=reverse_lazy('accounts:password_reset_done'),
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html'),
        name='password_reset_complete'),
]

apps/feed/urls.py
from django.conf.urls import url

from .views import HomeView, retrieve_new_post, get_feed_lists, get_recent_after, get_posts_before

urlpatterns = [
    url(r'^new-feed/(?P<post_id>[0-9a-f-]+)',
        retrieve_new_post, name="new_posts_retrieve_ajax"),
    url(r'^api/feeds/after/(?P<post_id>[0-9a-f-]+)', get_recent_after, name='get_recent_posts_ajax'),
    url(r'^api/feeds/before/(?P<post_id>[0-9a-f-]+)', get_posts_before, name='get_posts_before_ajax'),
    url(r'^api/feeds/', get_feed_lists, name='get_feed_list_ajax'),
    url(r'^$', HomeView.as_view(), name='home'),
]

apps/settings/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import settings_view

urlpatterns = [
    url(r'^$', settings_view, name='settings'),
    url(r'^change-password/$', auth_views.PasswordChangeView.as_view(template_name='change_password.html',
                                                                     success_url=reverse_lazy('settings:password_change_done')), name='change_password'),
    url(r'^change-password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='change_password_done.html'), name='password_change_done'),
]

apps/user_profile/urls.py
from django.conf.urls import url

from .views import follow_user, profile_photo, user_profile

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/$', user_profile, name='user_profile'),
    url(r'^(?P<username>[\w.@+-]+)/follow$', follow_user, name='follow_user'),
    url(r'^(?P<username>[\w.@+-]+)/profile_photo$',
        profile_photo, name="profile_photo"),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.templatetags.static import static as static_tag
from django.views.generic import RedirectView
from feed.views import LandingView

urlpatterns = [
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', LandingView.as_view(), name='landing_page'),
    url(r'^settings/', include('settings.urls', namespace='settings')),
    url(r'^user/', include('user_profile.urls', namespace='user_profile')),
    url(r'^', include('search.urls', namespace='search')),
    url(r'favicon.ico/$', RedirectView.as_view(
        url=static_tag('img/favicon.png'),
        permanent=True)),
    url(r'posts/', include('posts.urls', namespace='posts')),
    url(r'home/', include('feed.urls', namespace='feeds')),
]

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.errors.views.not_found'
handler500 = 'apps.errors.views.server_error'
handler403 = 'apps.errors.views.permission_denied'
handler400 = 'apps.errors.views.bad_request'

apps/accounts/models.py
# Create your models here.

apps/accounts/forms.py
"""Form handling for :accounts:."""
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(
        max_length=30, required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'First name',
                'required': 'required',
            }
        ))
    last_name = forms.CharField(
        max_length=30, required=True,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Last Name',
                'required': 'required',
            }
        ))
    email = forms.EmailField(
        max_length=254,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email',
                'required': 'required',
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',
                  'email', 'password1', 'password2',)


class CustomUserAuthenticationForm(AuthenticationForm):
    """
    CustomUserAuthForm with custom error message.

    Also, adds attributes to the input fields.
    """

    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Username',
                'required': 'required',
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
                'required': 'required',
            }
        )
    )
    AuthenticationForm.error_messages['inactive'] = _(
        "The email has not been verified. Please check your email\
        for verification link."
    )

apps/accounts/views.py
"""Views for :accounts: handling."""
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from .forms import CustomUserAuthenticationForm as UserAuthenticationForm
from .forms import SignUpForm
from .tokens import account_activation_token


def signup(request):
    if request.user.is_authenticated():
        return redirect('feeds:home')
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Welcome to Chirp.'
            message = render_to_string('accounts/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return render(request, 'accounts/email_sent.html', {'email': user.email})
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(
            request, ('Your account has been verified. Please login.'))
        messages.success(
            request, ('Your account has been verified. Please login.'))

        return redirect('feeds:home')

    else:

        return render(request, 'accounts/activation_error.html')


class UserLoginView(LoginView):
    """
    This handles login view.

    This logs in user using `UserAuthenticationForm`
    and redirects if user is already logged in.
    If there's `next` parameter, it redirects to it after :POST:.
    If login fails, the same view is shown with helpful error message.
    """

    template_name = 'accounts/login.html'
    authentication_form = UserAuthenticationForm
    redirect_authenticated_user = True


def logout_view(request):
    """Logout the user."""
    logout(request)
    return redirect('landing_page')

apps/accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},
Thank you for signing up at Chirp.
Please click on the link to confirm your registration,


<button ><a href="{% if request.is_secure %}https{% else %}http{% endif %}://{{ domain}}{% url 'accounts:activate' uidb64=uid token=token %}">Activate account</a></button>

In case link doesn't work please copy and paste the below url in a new tab:

{% if request.is_secure %}https{% else %}http{% endif %}://{{ domain}}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

apps/accounts/templates/accounts/activation_error.html
{% extends 'base.html' %}


{% block navbar %}

<style>
    .bg-w{
        background-color: rgba(20, 153, 60, 0.815);
            }
            .profile-img {
                margin-top: -5px;
                margin-right: 5px;
                float: left;
                background-size: auto 100%; /* Interchange this value depending on prefering width vs. height */
                width: 30px;
                height: 30px;
            }
</style>
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top  bg-w nav-down">

    <div class="container">
        <div class="navbar-translate">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'feeds:home' %}">Project Chirp</a>
            </div>
            <button class="navbar-toggler navbar-burger" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
            </button>
        </div>
    {% if user.is_authenticated %}
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                        <form action="" method="get" style="display: inline;" class="navbar-form navbar-left">
                                <div>
                                    <div class="input-group">

                                        <input type="text" class="form-control" style="margin-right:90px;" size="30" placeholder="Search" aria-describedby="basic-addon1">          

                                    </div>
                                </div>
                            </form>
                </li>
                <li class="nav-item">

                    <a class="nav-link" href="{% url 'feeds:home' %}#follow_friends" data-scroll="true" href="javascript:void(0)">Follow</a>
                </li>
                <li class="nav-item">

                        <a class="nav-link" href="{% url 'feeds:home' %}#trending_hashtags" data-scroll="true" href="javascript:void(0)">Trending</a>
                    </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown"><img src="{% if user.user_details.profile_photo %} {{ user.user_details.profile_photo.url }}{%else%}{% static 'img/default_profile.jpg' %}{% endif %}" class="img-circle img-no-padding img-responsive profile-img"></a>
                    <ul class="dropdown-menu dropdown-menu-right dropdown-danger">
                        <a class="dropdown-item" href="{% url 'user_profile:user_profile' username=user.username %}"><i class="fa fa-user"></i>&nbsp; Profile</a>
                        <a class="dropdown-item" href="{% url 'settings:settings' %}"><i class="nc-icon nc-settings"></i>&nbsp; Settings</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i>&nbsp; Logout</a>
                        <a class="dropdown-item" href="#with <3">Made with <i class="fa fa-heart" style="color:red;"></i>&nbsp; </a>
                    </ul>
                </li>
            </ul>
        </div>
    {% endif %}
    </div>
</nav>

{% endblock %}



{% block content %}





    
<div  id='textBox' > 
    <div class="emailSentText">
    <p id="box">
        The activation link is invalid. 
        Either the account is already activated or the link has expired.
    </p>
  </div>
</div>

<style>
  
  #textBox{
    position: absolute;
      top: 65%;
      left: 0;
      width: 100%;
      top: 95px;
      margin-top : 100px;
      text-align: center;
      
      line-height: 90px; 
  }

  .emailSentText {
      position: relative;
      top: 45%;
      left: 0;
      width: 100%;
      margin-left: 40px;
  }
  #box {
        border-radius: 25px;
        border: 2px solid #73AD21;
        padding: 20px; 
        width: 60%;
        margin-left: 20%;
        height: 80px; 
    }    
      
  
</style>
{% endblock %}

apps/accounts/templates/accounts/email_sent.html
{% extends 'base.html' %}


{% block navbar %}

<style>
    .bg-w{
        background-color: rgba(20, 153, 60, 0.815);
            }
            .profile-img {
                margin-top: -5px;
                margin-right: 5px;
                float: left;
                background-size: auto 100%; /* Interchange this value depending on prefering width vs. height */
                width: 30px;
                height: 30px;
            }
</style>
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top  bg-w nav-down">

    <div class="container">
        <div class="navbar-translate">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'feeds:home' %}">Project Chirp</a>
            </div>
            <button class="navbar-toggler navbar-burger" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
                <span class="navbar-toggler-bar"></span>
            </button>
        </div>
    {% if user.is_authenticated %}
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                        <form action="" method="get" style="display: inline;" class="navbar-form navbar-left">
                                <div>
                                    <div class="input-group">

                                        <input type="text" class="form-control" style="margin-right:90px;" size="30" placeholder="Search" aria-describedby="basic-addon1">          

                                    </div>
                                </div>
                            </form>
                </li>
                <li class="nav-item">

                    <a class="nav-link" href="{% url 'feeds:home' %}#follow_friends" data-scroll="true" href="javascript:void(0)">Follow</a>
                </li>
                <li class="nav-item">

                        <a class="nav-link" href="{% url 'feeds:home' %}#trending_hashtags" data-scroll="true" href="javascript:void(0)">Trending</a>
                    </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown"><img src="{% if user.user_details.profile_photo %} {{ user.user_details.profile_photo.url }}{%else%}{% static 'img/default_profile.jpg' %}{% endif %}" class="img-circle img-no-padding img-responsive profile-img"></a>
                    <ul class="dropdown-menu dropdown-menu-right dropdown-danger">
                        <a class="dropdown-item" href="{% url 'user_profile:user_profile' username=user.username %}"><i class="fa fa-user"></i>&nbsp; Profile</a>
                        <a class="dropdown-item" href="{% url 'settings:settings' %}"><i class="nc-icon nc-settings"></i>&nbsp; Settings</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i>&nbsp; Logout</a>
                        <a class="dropdown-item" href="#with <3">Made with <i class="fa fa-heart" style="color:red;"></i>&nbsp; </a>
                    </ul>
                </li>
            </ul>
        </div>
    {% endif %}
    </div>
</nav>

{% endblock %}



{% block content %}





    
<div  id='textBox' > 
    <div class="emailSentText">
    <p id="box">
        Email has been sent to: <strong>{{ email }}</strong>.
        Confirm email to continue your login.
    </p>
  </div>
</div>

<style>
  
  #textBox{
    position: absolute;
      top: 65%;
      left: 0;
      width: 100%;
      top: 95px;
      margin-top : 100px;
      text-align: center;
      
      line-height: 90px; 
  }

  .emailSentText {
      position: relative;
      top: 45%;
      left: 0;
      width: 100%;
      margin-left: 40px;
  }
  #box {
        border-radius: 25px;
        border: 2px solid #73AD21;
        padding: 20px; 
        width: 60%;
        margin-left: 20%;
        height: 80px; 
    }    
      
  
</style>
{% endblock %}

apps/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class="card card-register mx-auto">
        <h3 class="title">Welcome</h3>
        <form class="register-form" method="POST">
            {{form.non_field_errors}}
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-info btn-block btn-round">Login</button>
        </form>
        <div class="forgot">
            <a href="{%url 'accounts:password_reset'%}" class="btn btn-link btn-danger">Forgot password?</a>
        </div>
        <div class="no-account text-center">
            <a href="{% url 'accounts:signup' %}" class="btn btn-link btn-default">Don't have an account?</a>
        </div>
    </div>
</div>
{% endblock content %}

apps/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="card card-register mx-auto">

  <h2 class="title">Sign up</h2>
  <form class="register-form" method="POST">
      {{form.non_field_errors}}
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-info btn-block btn-round">Create account</button>
  </form>
  <br>
    <span>Already have an account? <a href="{% url 'accounts:login' %}">Login</a> </span>
  </div>

{% endblock %}