apps/settings/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import settings_view

urlpatterns = [
    url(r'^$', settings_view, name='settings'),
    url(r'^change-password/$', auth_views.PasswordChangeView.as_view(template_name='change_password.html',
                                                                     success_url=reverse_lazy('settings:password_change_done')), name='change_password'),
    url(r'^change-password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='change_password_done.html'), name='password_change_done'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.templatetags.static import static as static_tag
from django.views.generic import RedirectView
from feed.views import LandingView

urlpatterns = [
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', LandingView.as_view(), name='landing_page'),
    url(r'^settings/', include('settings.urls', namespace='settings')),
    url(r'^user/', include('user_profile.urls', namespace='user_profile')),
    url(r'^', include('search.urls', namespace='search')),
    url(r'favicon.ico/$', RedirectView.as_view(
        url=static_tag('img/favicon.png'),
        permanent=True)),
    url(r'posts/', include('posts.urls', namespace='posts')),
    url(r'home/', include('feed.urls', namespace='feeds')),
]

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.errors.views.not_found'
handler500 = 'apps.errors.views.server_error'
handler403 = 'apps.errors.views.permission_denied'
handler400 = 'apps.errors.views.bad_request'

apps/settings/models.py
# Create your models here.

apps/user_profile/forms.py
from datetime import date
from io import BytesIO

from django import forms
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage as storage
from PIL import Image

from .models import User_details


class UserForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control border-input', 'placeholder': 'First Name'}))
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control border-input', 'placeholder': 'First Name'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class UserDetailsForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control textarea-limited border-input', 'rows': '3', 'maxlength': '140'}), required=False)
    gender = forms.CharField(
        max_length=2,
        widget=forms.Select(choices=User_details.GENDER_CHOICES),
        required=False
    )
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'class': 'datetimepicker form-control'}),
                                    required=False)

    class Meta:
        model = User_details
        fields = ('bio', 'gender', 'date_of_birth')

    def clean_image(self, photo_name):
        image_file = photo_name
        if not image_file.name.endswith('.jpg'):
            raise forms.ValidationError("Only .jpg image accepted")
        return image_file

    def clean_date(self):
        birth_date = self.cleaned_data['date_of_birth']
        if birth_date > date.today():
            raise forms.ValidationError("The date cannot be in the Future.")


class ProfilePhotoForm(forms.ModelForm):
    profile_x = forms.FloatField(widget=forms.HiddenInput())
    profile_y = forms.FloatField(widget=forms.HiddenInput())
    profile_width = forms.FloatField(widget=forms.HiddenInput())
    profile_height = forms.FloatField(widget=forms.HiddenInput())
    DIMENSIONS = (200, 200)

    class Meta:
        model = User_details
        fields = ('profile_photo', 'profile_x', 'profile_y',
                  'profile_height', 'profile_width')
        widgets = {
            'profile_photo': forms.FileInput(attrs={'accept': 'image/jpeg'})
        }

    def save(self):
        photo = super(ProfilePhotoForm, self).save()
        x = self.cleaned_data.get('profile_x')
        y = self.cleaned_data.get('profile_y')
        w = self.cleaned_data.get('profile_width')
        h = self.cleaned_data.get('profile_height')

        clean_image_file = UserDetailsForm.clean_image(
            self, photo.profile_photo)
        image = Image.open(clean_image_file)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize(self.DIMENSIONS, Image.ANTIALIAS)
        new_image_io = BytesIO()
        resized_image.save(new_image_io, format='JPEG')
        temp_name = photo.profile_photo.name
        photo.profile_photo.save(
            temp_name,
            content=ContentFile(new_image_io.getvalue()),
            save=False
        )
        return super(ProfilePhotoForm, self).save()
        # fh = storage.open(photo.profile_photo.name, "w")
        # format = 'jpeg'
        # resized_image.save(fh, format)
        # fh.close()

        # return resized_image


class CoverPhotoForm(forms.ModelForm):
    cover_x = forms.FloatField(widget=forms.HiddenInput())
    cover_y = forms.FloatField(widget=forms.HiddenInput())
    cover_width = forms.FloatField(widget=forms.HiddenInput())
    cover_height = forms.FloatField(widget=forms.HiddenInput())
    DIMENSIONS = (1357, 334)

    class Meta:
        model = User_details
        fields = ('cover_photo', 'cover_x', 'cover_y',
                  'cover_height', 'cover_width')
        widgets = {
            'cover_photo': forms.FileInput(attrs={'accept': 'image/jpeg'})
        }

    def save(self):
        photo = super(CoverPhotoForm, self).save()
        x = self.cleaned_data.get('cover_x')
        y = self.cleaned_data.get('cover_y')
        w = self.cleaned_data.get('cover_width')
        h = self.cleaned_data.get('cover_height')

        clean_image_file = UserDetailsForm.clean_image(self, photo.cover_photo)
        image = Image.open(clean_image_file)
        cropped_image = image.crop((x, y, w + x, h + y))
        resized_image = cropped_image.resize(self.DIMENSIONS, Image.ANTIALIAS)
        new_image_io = BytesIO()
        resized_image.save(new_image_io, format='JPEG')
        temp_name = photo.cover_photo.name
        photo.cover_photo.save(
            temp_name,
            content=ContentFile(new_image_io.getvalue()),
            save=False
        )
        return super(CoverPhotoForm, self).save()
        # fh = storage.open(photo.cover_photo.name, "w")
        # format = image.format
        # resized_image.save(fh, format)
        # fh.close()

        # return resized_image

apps/settings/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db import transaction
from django.shortcuts import redirect, render

from user_profile.forms import (CoverPhotoForm, ProfilePhotoForm,
                                UserDetailsForm, UserForm)


def profile_photo_view(request):
    profile_photo_form = ProfilePhotoForm(
        request.POST, request.FILES, instance=request.user.user_details)
    if profile_photo_form.is_valid():
        profile_photo_form.save()
        messages.success(
            request, ('Your profile Photo was successfully updated!'))
        return redirect(reverse('user_profile:user_profile', kwargs={'username': request.user.username}))
    else:
        messages.error(request, ('Cant update profile photo'))


def cover_photo_view(request):
    cover_photo_form = CoverPhotoForm(
        request.POST, request.FILES, instance=request.user.user_details)
    if cover_photo_form.is_valid():
        cover_photo_form.save()
        messages.success(
            request, ('Your cover Photo was successfully updated!'))
        return redirect(reverse('user_profile:user_profile', kwargs={'username': request.user.username}))
    else:
        messages.error(request, ('Cant update cover photo'))


@login_required
@transaction.atomic
def settings_view(request):
    if request.method == 'POST':
        if 'profile_submit_button' in request.POST:
            return profile_photo_view(request)

        if 'cover_submit_button' in request.POST:
            return cover_photo_view(request)

        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserDetailsForm(
            request.POST, instance=request.user.user_details)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.date_of_birth = profile_form.clean_date()
            profile_form.save(commit=False)
            profile_form.user = request.user
            profile_form.save()
            messages.success(
                request, ('Your profile was successfully updated!'))
            return redirect(reverse('user_profile:user_profile', kwargs={'username': request.user.username}))
        else:
            messages.error(request, ('Please correct the error below.'))
    elif request.method == 'GET':
        user_form = UserForm(instance=request.user)
        profile_form = UserDetailsForm(instance=request.user.user_details)
        profile_photo_form = ProfilePhotoForm(
            instance=request.user.user_details)
        cover_photo_form = CoverPhotoForm(instance=request.user.user_details)

        return render(request, 'settings.html', {
            'user_form': user_form,
            'profile_form': profile_form,
            'profile_photo_form': profile_photo_form,
            'cover_photo_form': cover_photo_form,

        })

apps/settings/templates/change_password.html
{% extends 'base.html' %}
{% block content %}
<div class="card card-register mx-auto">
        <h3 class="title">Change Password</h3>
        <form class="register-form" method="POST">
            {{form.non_field_errors}}
            {% csrf_token %}
            {{ form.as_p }}
        <form class="register-form" method="POST">
            <button class="btn btn-info btn-block btn-round">Change Password</button>
        </form>
    </div>
</div>
{% endblock content %}

apps/settings/templates/change_password_done.html
{% extends 'base.html' %}
{% block content %}
<div class="card card-register mx-auto">
        <h3 class="title">Change Password</h3>
        <h4>Your Password has been changed successfully.</h4>
            <a href="{% url 'Home' %}"<button class="btn btn-info btn-block btn-round">Home Page</button>
    </div>
</div>
{% endblock content %}

apps/settings/templates/settings.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="wrapper">
    {% include 'cover_photo.html' %}

    {% include 'profile_details.html' %}

                          <!-- FORM TO UPLOAD THE IMAGES -->
<div class="row d-flex justify-content-center">
    <form method="post" enctype="multipart/form-data" id="profile_photo">
      {% csrf_token %}
      {{ profile_photo_form }}
      <input type="submit" hidden id="profile_submit_button" name="profile_submit_button">
  </form>
  <form method="post" enctype="multipart/form-data" id="cover_photo">
    {% csrf_token %}
    {{ cover_photo_form }}
    <input type="submit" hidden id="cover_submit_button" name="cover_submit_button">
  </form>
</div>
                    </div>
                    </div>

                </div>

                <div class="row d-flex justify-content-center">
                    <div class="col-md-6 col-md-offset-3">
                            <form class="settings-form" method="POST" enctype="multipart/form-data" id="formUpload">
                                {{form.non_field_errors}}
                                {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <label>First Name</label>
                                        {{ user_form.first_name }}
                                    </div>
                                </div>

                                <div class="col-md-6 col-sm-6">
                                    <div class="form-group">
                                        <label>Last Name</label>
                                        {{ user_form.last_name }}                                    </div>
                                </div>
                            </div>
                          <div class="form-group">
                            <label>Bio</label>
                            {{ profile_form.bio }}
                          </div>
                          <div class="form-group">
                                <label>Gender</label>
                                {{ profile_form.gender }}
                              </div>
                              <div class="form-group">
                                  <label>Date of Birth: (YYYY-MM-DD)</label>
                                  <div class="row input-group date" id="datetimepicker">
                                        {{ profile_form.date_of_birth }}
                                        <span class="input-group-addon">
                                          <span class="glyphicon glyphicon-calendar"><i class="fa fa-calendar" aria-hidden="true"></i></span>
                                      </span>
                                  </div></div>

<label>Account Settings</label>
                          <ul class="notifications" style="list-style-type: none;">
                              <li class="notification-item">
                                 <div class="row">
                                      <div class="col-xs-9">
                                        <a href="{%url 'settings:change_password' %}"><b>Change Password</b></a>
                                      </div>
                                  </div>
                              </li>
                          </ul>

                                                    <div class="row d-flex justify-content-center">
                              <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                                <button type="submit" class="btn btn-block btn-info">Save</button>
                              </div>
                          </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
                    <!-- MODAL TO CROP THE IMAGE -->
                    <div class="modal fade" id="modalCrop">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title">Crop the photo</h4>
                          </div>
                          <div class="modal-body">
                            <img src="" id="image" style="max-width: 100%;">
                          </div>
                          <div class="modal-footer">
                            <div class="btn-group pull-left" role="group">
                              <button type="button" class="btn btn-default js-zoom-in">
                                <span class="fa fa-plus"></span>
                              </button>
                              <button type="button" class="btn btn-default js-zoom-out">
                                <span class="fa fa-minus"></span>
                              </button>
                              <input type="text" hidden id="status">
                            </div>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
                            <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
                          </div>
                        </div>
                      </div>
                    </div>
    {% block javascripts %}
  <script>
    var size_x, size_y;
  $('#id_cover_photo').on("change", function() {
      if(! window.FileReader){console.log('Not supported.')}
      var browse_btn = $('#id_cover_photo')[0];
      file = browse_btn.files[0];
        if (file) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
            $('#status')[0].value = '0';
            size_x = 1357;
            size_y = 334;
            aspect_ratio = 9/2;
          };
          reader.readAsDataURL(file);
        }
      
    });

    $('#id_profile_photo').on("change", function() {
      if(! window.FileReader){console.log('Not supported.')}
      var browse_btn = $('#id_profile_photo')[0];
        file = browse_btn.files[0];
        if (file) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
            $('#status')[0].value = '1';
            size_x = 200;
            size_y = 200;
            aspect_ratio = 1/1;
          };
          var css = document.createElement("style");
          css.type = "text/css";
          css.innerHTML = "  .cropper-crop-box, .cropper-view-box {border-radius: 50%;} .cropper-view-box {box-shadow: 0 0 0 1px #39f;outline: 0;";
          document.body.appendChild(css);
          reader.readAsDataURL(file);}
      
    });


      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData = {
        width: size_x,
        height: size_y
      };
      var canvasData= {
        width: size_x,
        height: size_y
      };
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: aspect_ratio,
          minCropBoxWidth: size_x,
          minCropBoxHeight: size_y,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
            $image.cropper;

          }
          
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        // $("#id_x").val(cropData["x"]);
        // $("#id_y").val(cropData["y"]);
        // $("#id_height").val(cropData["height"]);
        // $("#id_width").val(cropData["width"]);
        if ($('#status')[0].value === '1'){
        $("#id_profile_x").val(cropData["x"]);
        $("#id_profile_y").val(cropData["y"]);
        $("#id_profile_height").val(cropData["height"]);
        $("#id_profile_width").val(cropData["width"]);
          $("#profile_submit_button").click();
        }
        else if ($('#status')[0].value === '0'){
        $("#id_cover_x").val(cropData["x"]);
        $("#id_cover_y").val(cropData["y"]);
        $("#id_cover_height").val(cropData["height"]);
        $("#id_cover_width").val(cropData["width"]);
          $("#cover_submit_button").click();
        }
        else{
          // do nothing 
        }
      });

  </script>
{% endblock javascripts %}



{% endblock content %}