apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy

from .views import activate as activate_view
from .views import UserLoginView, logout_view, signup

app_name = 'accounts'
urlpatterns = [
    url(r'signup/$', signup, name='signup'),
    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate_view, name='activate'),

    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt',
            success_url=reverse_lazy('accounts:password_reset_done'),
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(
            template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url=reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html'),
        name='password_reset_complete'),
]

apps/feed/urls.py
from django.conf.urls import url

from .views import HomeView, retrieve_new_post, get_feed_lists, get_recent_after, get_posts_before

urlpatterns = [
    url(r'^new-feed/(?P<post_id>[0-9a-f-]+)',
        retrieve_new_post, name="new_posts_retrieve_ajax"),
    url(r'^api/feeds/after/(?P<post_id>[0-9a-f-]+)', get_recent_after, name='get_recent_posts_ajax'),
    url(r'^api/feeds/before/(?P<post_id>[0-9a-f-]+)', get_posts_before, name='get_posts_before_ajax'),
    url(r'^api/feeds/', get_feed_lists, name='get_feed_list_ajax'),
    url(r'^$', HomeView.as_view(), name='home'),
]

apps/search/urls.py
from django.conf.urls import url

from apps.search import views as search_views

urlpatterns = [
    # For autocomplete suggestions
    # url(r'^autocomplete/$', search_views.get_autocomplete_suggestions, name='autocomplete'),
    url(r'^search/$', search_views.search, name='search'),
]

apps/settings/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import settings_view

urlpatterns = [
    url(r'^$', settings_view, name='settings'),
    url(r'^change-password/$', auth_views.PasswordChangeView.as_view(template_name='change_password.html',
                                                                     success_url=reverse_lazy('settings:password_change_done')), name='change_password'),
    url(r'^change-password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='change_password_done.html'), name='password_change_done'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.templatetags.static import static as static_tag
from django.views.generic import RedirectView
from feed.views import LandingView

urlpatterns = [
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^$', LandingView.as_view(), name='landing_page'),
    url(r'^settings/', include('settings.urls', namespace='settings')),
    url(r'^user/', include('user_profile.urls', namespace='user_profile')),
    url(r'^', include('search.urls', namespace='search')),
    url(r'favicon.ico/$', RedirectView.as_view(
        url=static_tag('img/favicon.png'),
        permanent=True)),
    url(r'posts/', include('posts.urls', namespace='posts')),
    url(r'home/', include('feed.urls', namespace='feeds')),
]

if settings.DEBUG:
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.errors.views.not_found'
handler500 = 'apps.errors.views.server_error'
handler403 = 'apps.errors.views.permission_denied'
handler400 = 'apps.errors.views.bad_request'

chirp/templates/a.html
<body>
    <head>{%load static%}
<link rel="stylesheet" href="{%static 'css/a.css'%}">
</head>
<h1>Hi

</h1>
</body>

chirp/templates/alert_message.html
<div class="messages col-sm-3 col-sm-offset-8">
    <div class="alert" data-notify="container">
        {% for message in messages %}

        <div class="container container-alert-message">
            <div class="alert-wrapper alert alert-{{ message.tags }}">
                <div class="message text-center">{{ message }} </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

chirp/templates/b.html
<html>
    <head>
{% load static %}
<link rel="stylesheet" href="{%static 'css/a.css'%}">
</head>
    <body>
        <form action="{% url 'upload_pic' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" name="upload">
        </form>
{% if all_images %}
    {% for image in all_images %}
        <p>
            <img src="{{ image.file.url }}" />
        </p>
    {% endfor %}
{% endif %}
    </body>
</html>

chirp/templates/base_accounts.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Chirp{% endblock %}</title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' name='viewport' />
  <meta name="viewport" content="width=device-width" />
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link href="{% static  'css/paper-kit.css' %}" rel="stylesheet"/>
  {%block stylesheet%}{%endblock%}
  <style>
    body { padding-top: 70px;
     background-color:seashell;
    }
    
    .navbar
    {
      background:rgb(62, 170, 93) !important;
      padding-top:0px !important; padding-bottom:0px !important;
    }
    .navbar .navbar-brand {
    font-weight: 600;
    margin: 5px auto !important;
    padding: 20px 15px;
    font-size: 22px !important;
    }
    p input{
      border-radius:5px;
      background-color:transparent;
      border:1px solid black;
      text-align:center;
      font-family: 'Courier New', Courier, monospace;
      font-size:15px;
      width:100%;
      height: 30px;
    }
    .container{
      font-family:Arial, Helvetica, sans-serif;
    }
    p{
      font-size: 16px;
      font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
      width:100%;

    }
  </style>
</head>
<body>
  {% include 'navbar.html' %}
  <div class="container">
    <h5 class="text-center logo my-4">
      <a href="{% url 'feeds:home'%}">Back to Home</a>
    </h5>      
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

chirp/templates/cover_photo.html
{% load static %}
    {% if not profile_user %}
        {% with profile_user=user %}
            <div class="page-header page-header-small"  style="background-image: url('{% if profile_user.user_details.cover_photo %} {{ profile_user.user_details.cover_photo.url }}{%else%}{% static 'img/default_cover.png' %}{% endif %}');"></div>
        {% endwith %}
    {% else %}
        <div class="page-header page-header-small"  style="background-image: url('{% if profile_user.user_details.cover_photo %} {{ profile_user.user_details.cover_photo.url }}{%else%}{% static 'img/default_cover.png' %}{% endif %}');"></div>
    {% endif %}
    <div class="filter"></div>
</div>

chirp/templates/landing.html
{% load static %}
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome to Project Chirp</title>
    <link href="{% static  'css/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static  'css/paper-kit.css' %}" rel="stylesheet"/>
	<link href='https://fonts.googleapis.com/css?family=Montserrat:400,300,700' rel='stylesheet' type='text/css'>
</head>
<body>
        <nav class="navbar navbar-expand-lg fixed-top navbar-transparent" color-on-scroll="300">
                <div class="container">
                    <div class="navbar-translate">
                            <a class="navbar-brand" href="{% url 'landing_page' %}">Project Chirp</a>
                            <button class="navbar-toggler navbar-toggler-right navbar-burger" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-bar"></span>
                            <span class="navbar-toggler-bar"></span>
                            <span class="navbar-toggler-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="navbarToggler">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                    <li class="navbar-brand">Already a User?</li>
                                <a href="{% url 'accounts:login' %}" class="nav-link"><button type="button" class="btn btn-outline-neutral btn-round">Log In</button></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        
                <div class="page-header" data-parallax="true" style="background-image: url('{% if debug %} {% static "img/2343233802702119897.jpg" %} {% else %} https://source.unsplash.com/collection/1215308/social-media {% endif %}');">
                    <div class="filter"></div>
                    <div class="container">
                        <div class="motto text-center">
                            <h1>Welcome to Project Chirp</h1>
                            <h3>Share your thoughts and Connect with People.</h3>
                            <br />
                            <a href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-outline-neutral btn-round">Join Now!</button></a>
                        </div>
                    </div>
                </div>
</body>
</html>

chirp/templates/navbar.html
<style>
    .bg-w{
        background-color: rgba(20, 153, 60, 0.815);
    }
    .profile-img {
        margin-top: -5px;
        margin-right: 5px;
        float: left;
        background-size: auto 100%; /* Interchange this value depending on prefering width vs. height */
        width: 30px;
        height: 30px;
    }
    #navbarToggler {
        display:block !important; /*ct-paper diplay:none override*/
    }
    .navbar.navbar-transparent {
        padding: 0px !important ;
    }
    .navbar {
        padding:0px !important;
        min-height:32px !important;
    }
    .search-bar::placeholder { /* Most modern browsers support this now. */
        color:rgb(68, 230, 122)  !important; 
        font-weight:500 !important;
        text-align: center !important;
    }
    .search-bar input{
        color:#02856f !important;
        font-weight:bold !important;
        -webkit-border-radius: 5px !important;
        -moz-border-radius: 5px !important;
        border-radius: 5px !important;
        width:100% !important;
        text-align: center !important;
    }
    
    ::-ms-clear {
        display: none;
    }
    
    .form-control-clear {
        z-index: 10;
        pointer-events: auto;
        cursor: pointer;
    }
    .hidden {
        visibility: hidden; /* If you want to reserve space */
    }
    .visible {
        visibility: show; /* If you want to reserve space */
    }
</style>
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top navbar-transparent bg-w nav-down" color-on-scroll="200">
    <div class="container">
        <a class="navbar-brand" href="{% url 'feeds:home' %}">Project Chirp</a>
        
        <button class="navbar-toggler navbar-burger" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar"></span>
            <span class="navbar-toggler-bar"></span>
            <span class="navbar-toggler-bar"></span>
        </button>
        
        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarToggler" style="padding-left:0;text-align:center;">            
            <ul class="navbar-nav ml-auto">
                
                <li class="nav-item mx-auto">
                    <form role ="search" action="{% url 'search:search' %}" method="get" style="display: inline;" class="navbar-form navbar-left">
                        <div>
                            <input type="hidden" name="type">
                            <div class="input-group has-feedback has-clear search-bar">
                                
                                    <input type="text" id="auto-search" name="q" class="form-control"  size="30" placeholder="Search"  value="{{ querystring }}" aria-describedby="basic-addon1">          
                                    <i class="form-control-clear fa fa-remove form-control-feedback hidden" style="padding-left:0px;margin-top:-10px; color:#02856f;" ></i>
                             </div>
                        </div>
                    </form>
                </li>
                
                <li class="nav-item">
                    
                    <a class="nav-link" href="{% url 'feeds:home' %}#follow_friends" data-scroll="true" href="javascript:void(0)">Follow</a>
                </li>
                <li class="nav-item">
                    
                    <a class="nav-link" href="{% url 'feeds:home' %}#trending_hashtags" data-scroll="true" href="javascript:void(0)">Trending</a>
                </li>
                <li class="nav-item dropdown d-none d-lg-block">
                    <a class="nav-link dropdown-toggle" id="dropdownMenuButton" href="javascript:void(0)" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="{% if user.user_details.profile_photo %} {{ user.user_details.profile_photo.url }}{%else%}{% static 'img/default_profile.jpg' %}{% endif %}" class="img-circle img-no-padding img-responsive profile-img"></a>
                    <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'user_profile:user_profile' username=user.username %}"><i class="fa fa-user"></i>&nbsp; Profile</a>
                        <a class="dropdown-item" href="{% url 'settings:settings' %}"><i class="nc-icon nc-settings"></i>&nbsp; Settings</a>
                        <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i>&nbsp; Logout</a>
                        <a class="dropdown-item" href="#with <3">Made with <i class="fa fa-heart" style="color:red;"></i>&nbsp; </a>
                    </ul>
                </li>
                <li class="nav-item d-md-none">
                        <a class="nav-link" href="{% url 'user_profile:user_profile' username=user.username %}"><i class="fa fa-user"></i>&nbsp; Profile</a>
                        </li>
                        <li class="nav-item d-md-none">
                        <a class="nav-link" href="{% url 'settings:settings' %}"><i class="nc-icon nc-settings"></i>&nbsp; Settings</a>
                        </li>
                        <li class="nav-item d-md-none">

                        <a class="nav-link" href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i>&nbsp; Logout</a>
                        </li>
                        <li class="nav-item d-md-none">
                        <a class="nav-link" href="#with <3">Made with <i class="fa fa-heart" style="color:red;"></i>&nbsp; </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        {% endif %}
    </div>
</nav>

chirp/templates/profile_details.html
{% load static %}
{% load check_followed_filter %}

<div class="row owner">
    {% if not profile_user %}
        {% with profile_user=user %}
        <div class="col-md-2 col-sm-4 col-6 ml-auto mr-auto text-center">
            <div class="avatar">
                <img src="{% if profile_user.user_details.profile_photo %} {{ profile_user.user_details.profile_photo.url }}{%else%}{% static 'img/default_profile.jpg' %}{% endif %}" alt="Circle Image" class="img-circle img-responsive">
            </div>
            <div class="name">

                <a href="{% url 'user_profile:user_profile' username=profile_user.username %}">
                    <h5>{{profile_user.first_name}} {{profile_user.last_name}} <br />
                        <small>@{{profile_user.username}}</small>
                        <a href="{% url 'settings:settings' %}">
                            <i class="fa fa-cog"></i>
                        </a>
                    </h5>
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 ml-auto mr-auto text-center">
            <p>
                {% if profile_user.user_details.bio %}
                    {{ profile_user.user_details.bio }}
                {% endif %}
            </p>
            <div class="description-details">
                <ul class="list-unstyled">
                        <li>{% if profile_user.user_details.gender == 'M' %}
                                <i class="fa fa-male"></i>Male
                            {% elif profile_user.user_details.gender == 'F' %}
                                <i class="fa fa-female"></i>Female
                            {% else %}
                            <i></i>
                            {% endif %}
                        <li>
                            {% if profile_user.user_details.date_of_birth %}
                                <i class="fa fa-calendar"></i>
                                Born {{ profile_user.user_details.date_of_birth }}
                            {% endif %}
                        </li>
                </ul>
            </div>
        </div>

        {% endwith %}
        {% else %}
        <div class="col-md-2 col-sm-4 col-6 ml-auto mr-auto text-center">
                <div class="avatar">
                    <img src="{% if profile_user.user_details.profile_photo %} {{ profile_user.user_details.profile_photo.url }}{%else%}{% static 'img/default_profile.jpg' %}{% endif %}" alt="Circle Image" class="img-circle img-responsive">
                     {% if profile_user != user %}
                    <div class="following">
                        {% if user|check_followed_user_already:profile_user %}
                            <a href="{% url 'user_profile:follow_user' username=profile_user.username %}">
                                <btn class="btn btn-info btn-round" rel="tooltip" title="Follow"><i class="fa fa-user-times"></i>Unfollow</btn>
                            </a>
                        {% else %}
                            <a href="{% url 'user_profile:follow_user' username=profile_user.username %}">
                                <btn class="btn btn-info btn-round" rel="tooltip" title="Follow">
                                    <i class="fa fa-user-plus"></i>Follow
                                </btn>
                            </a>
                        {% endif %}
                    </div>
                    {% endif %}
                </div>
                <div class="name">
                     <a href="{% url 'user_profile:user_profile' username=profile_user.username %}">
                         <h4>{{profile_user.first_name}} {{profile_user.last_name}} <br />
                            <small>@{{profile_user.username}}</small>
                            {% if profile_user == user %}
                                <a href="{% url 'settings:settings' %}">
                                    <i class="fa fa-cog"></i>
                                </a>
                            {% endif %}
                        </h4>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 ml-auto mr-auto text-center">
                <p>{% if profile_user.user_details.bio %}{{ profile_user.user_details.bio }}{% endif %}</p>
                <div class="description-details">
                    <ul class="list-unstyled">
                            <li>{% if profile_user.user_details.gender == 'M' %}
                                    <i class="fa fa-male"></i>Male
                                {% elif profile_user.user_details.gender == 'F' %}
                                    <i class="fa fa-female"></i>Female
                                {% else %}
                                    <i></i>
                                {% endif %}
                            <li>
                                {% if profile_user.user_details.date_of_birth %}
                                    <i class="fa fa-calendar"></i>
                                    Born {{ profile_user.user_details.date_of_birth }}
                                {% endif %}
                            </li>
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>